name: Deploy Angular to VPS (Apache)

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Build Angular (prod)
        run: npm run build -- --configuration production

      - name: Inspect dist
        run: |
          ls -la dist
          ls -la dist/* || true
          ls -la dist/*/browser || true

      - name: Create remote folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_KEY_PASS }}
          script: |
            mkdir -p "${{ secrets.VPS_PATH }}"

      - name: Upload build to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_KEY_PASS }}
          source: "dist/AngularContinuo/browser/"
          target: "${{ secrets.VPS_PATH }}"
          strip_components: 3
          overwrite: true

      - name: Check remote files after upload
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_KEY_PASS }}
          script: |
            echo "USER: $(whoami)"
            echo "VPS_PATH: ${{ secrets.VPS_PATH }}"
            ls -la "${{ secrets.VPS_PATH }}" || true
            echo "index.html found:"
            find "${{ secrets.VPS_PATH }}" -maxdepth 3 -name index.html -print 2>/dev/null || true
